import type { Tool, Category, TagColor } from './types';
import { 
  AllCategoriesIcon, ReconnaissanceIcon, WebAppIcon, PostExploitationIcon, 
  ThreatIntelIcon, AISecurityIcon, DFIRIcon, DetectionIcon, DevSecOpsIcon, 
  IoTSecurityIcon, MalwareAnalysisIcon, ExploitationFrameworksIcon, RedTeamOpsIcon,
  VulnerabilityScanningIcon, NetworkPenetrationIcon, SecurityAuditingIcon,
  WirelessHackingIcon, C2Icon, MobileSecurityIcon, SocialEngineeringIcon, LockIcon, StarIcon
} from './components/Icons';

export const categories: Category[] = [
  { id: 'all', name: 'All Categories', count: 1253, icon: AllCategoriesIcon },
  { id: 'favorites', name: 'Favorites', count: 0, icon: StarIcon },
  { id: 'recon', name: 'Reconnaissance and OSINT', count: 260, icon: ReconnaissanceIcon },
  { id: 'websec', name: 'Web Application Security', count: 118, icon: WebAppIcon },
  { id: 'postexploit', name: 'Post-Exploitation', count: 68, icon: PostExploitationIcon },
  { id: 'threatintel', name: 'Threat Intelligence', count: 58, icon: ThreatIntelIcon },
  { id: 'aisec', name: 'AI Security', count: 56, icon: AISecurityIcon },
  { id: 'dfir', name: 'DFIR', count: 50, icon: DFIRIcon },
  { id: 'detection', name: 'Detection and Response', count: 45, icon: DetectionIcon },
  { id: 'devsecops', name: 'DevSecOps Tools', count: 38, icon: DevSecOpsIcon },
  { id: 'iot', name: 'IoT Security', count: 36, icon: IoTSecurityIcon },
  { id: 'malware', name: 'Malware Analysis', count: 34, icon: MalwareAnalysisIcon },
  { id: 'exploitfw', name: 'Exploitation Frameworks', count: 32, icon: ExploitationFrameworksIcon },
  { id: 'redteamops', name: 'Red Team Operations', count: 33, icon: RedTeamOpsIcon },
  { id: 'vulnscan', name: 'Vulnerability Scanning', count: 31, icon: VulnerabilityScanningIcon },
  { id: 'netpen', name: 'Network Penetration', count: 31, icon: NetworkPenetrationIcon },
  { id: 'secaudit', name: 'Security Auditing', count: 31, icon: SecurityAuditingIcon },
  { id: 'wireless', name: 'Wireless Hacking', count: 30, icon: WirelessHackingIcon },
  { id: 'c2', name: 'Command and Control (C2)', count: 29, icon: C2Icon },
  { id: 'mobilesec', name: 'Mobile Security', count: 27, icon: MobileSecurityIcon },
  { id: 'socialeng', name: 'Social Engineering', count: 27, icon: SocialEngineeringIcon },
  { id: 'persistence', name: 'Persistence Techniques', count: 0, icon: PostExploitationIcon },
  { id: 'secaware', name: 'Security Awareness', count: 0, icon: VulnerabilityScanningIcon },
  { id: 'passattacks', name: 'Password Attacks', count: 0, icon: LockIcon },
];

export const tagColors = ['red', 'blue', 'green', 'yellow', 'purple', 'indigo', 'pink'] as const;

export const initialTools: Tool[] = [
  {
    id: 'mangle',
    name: 'Mangle',
    description: 'A tool that manipulates aspects of compiled executables (exe or DLL). Mangle can remove known Indicators of Compromise (IoC) based strings and replace them with random characters, change the file by inflating the size to avoid EDRs, and can clone code-signing certs from legitimate files. In doing so, Mangle...',
    link: '#',
    // NOTE: The native Picture-in-Picture API requires a direct link to a video file (.mp4, .webm, etc.).
    // Standard YouTube "watch" links will not work. This URL is a placeholder for demonstration.
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    author: { name: 'João Paulo de Andrade Filho', avatarUrl: 'https://picsum.photos/seed/jp/32/32' },
    imageUrl: 'https://i.imgur.com/kYmO3P3.png',
    category: 'Persistence Techniques',
    tagColor: 'red',
    rating: 5,
  },
  {
    id: 'onionland',
    name: 'OnionLand',
    description: 'Gateway enabling anonymous, secure access and search of .onion sites on the dark web.',
    link: '#',
    author: { name: 'Marcos Henrique', avatarUrl: 'https://picsum.photos/seed/mh/32/32' },
    imageUrl: 'https://i.imgur.com/R3iUzgK.png',
    category: 'Reconnaissance and OSINT',
    tagColor: 'red',
    rating: 4,
  },
  {
    id: 'sharplateral',
    name: 'SharpLateral',
    description: 'C# tool for lateral movement in Active Directory environments.',
    link: '#',
    author: { name: 'Marcos Henrique', avatarUrl: 'https://picsum.photos/seed/mh/32/32' },
    imageUrl: 'https://i.imgur.com/gO07M3o.png',
    category: 'Post-Exploitation',
    tagColor: 'red',
    rating: 4,
  },
  {
    id: 'shellcode-exec',
    name: 'Shellcode Exec',
    description: 'Open-source script to execute in-memory shellcode across different architectures and OSes.',
    link: '#',
    author: { name: 'Marcos Henrique', avatarUrl: 'https://picsum.photos/seed/mh/32/32' },
    imageUrl: 'https://i.imgur.com/sNfIZz2.png',
    category: 'Exploitation Frameworks',
    tagColor: 'red',
    rating: 5,
  },
  {
    id: 'sotwe',
    name: 'sotwe',
    description: 'Twitter viewer tracking trends, top users, hashtags and locations for OSINT insights.',
    link: '#',
    author: { name: 'Marcos Henrique', avatarUrl: 'https://picsum.photos/seed/mh/32/32' },
    imageUrl: 'https://i.imgur.com/yL7bE5v.png',
    category: 'Reconnaissance and OSINT',
    tagColor: 'red',
    rating: 4,
  },
  {
    id: 'swaggerjacker',
    name: 'SwaggerJACKER',
    description: 'sj is a command line tool designed to assist with auditing of exposed Swagger/OpenAPI definition files by checking the associated API endpoints for weak authentication. It also provides command templates for manual vulnerability testing.',
    link: '#',
    author: { name: 'Marcos Henrique', avatarUrl: 'https://picsum.photos/seed/mh/32/32' },
    imageUrl: 'https://i.imgur.com/4z8gVnC.png',
    category: 'Web Application Security',
    tagColor: 'blue',
    rating: 4,
  },
  {
    id: 'gemini-cli',
    name: 'Gemini CLI',
    description: 'Gemini CLI automates tasks, builds apps, and interacts with code using multimodal AI.',
    link: '#',
    author: { name: 'Marcos Henrique', avatarUrl: 'https://picsum.photos/seed/mh/32/32' },
    imageUrl: 'https://i.imgur.com/i7H5WfC.png',
    category: 'AI Security',
    tagColor: 'indigo',
    rating: 5,
  },
  {
    id: 'freeway',
    name: 'FREEWAY',
    description: 'Python Scapy-based tool for WiFi penetration testing and auditing home or enterprise networks.',
    link: '#',
    author: { name: 'Marcos Henrique', avatarUrl: 'https://picsum.photos/seed/mh/32/32' },
    imageUrl: 'https://i.imgur.com/tHqgG9R.png',
    category: 'Wireless Hacking',
    tagColor: 'green',
    rating: 4,
  },
   {
    id: 'red-teaming-llm',
    name: 'Red Teaming LLM',
    description: 'Adapted code to test LLMs and find flaws using Azure OpenAI endpoints.',
    link: '#',
    author: { name: 'Marcos Henrique', avatarUrl: 'https://picsum.photos/seed/mh/32/32' },
    imageUrl: 'https://i.imgur.com/hO5e8R2.png',
    category: 'AI Security',
    tagColor: 'indigo',
    rating: 4,
  },
  {
    id: 'justdelete',
    name: 'justdelete',
    description: 'Directory of direct links to delete user accounts from many web services.',
    link: '#',
    author: { name: 'Marcos Henrique', avatarUrl: 'https://picsum.photos/seed/mh/32/32' },
    imageUrl: 'https://i.imgur.com/4oW5sQ5.png',
    category: 'Security Awareness',
    tagColor: 'purple',
    rating: 4,
  },
  {
    id: 'hunter',
    name: 'HUNTER',
    description: 'Search engine to identify exposed internet-connected devices and services.',
    link: '#',
    author: { name: 'Marcos Henrique', avatarUrl: 'https://picsum.photos/seed/mh/32/32' },
    imageUrl: 'https://i.imgur.com/3D1T6Pq.png',
    category: 'Reconnaissance and OSINT',
    tagColor: 'red',
    rating: 5,
  },
   {
    id: 'uh0h365',
    name: 'UhOh365',
    description: 'Validates Office365 emails without login, useful for enumeration and social engineering.',
    link: '#',
    author: { name: 'Marcos Henrique', avatarUrl: 'https://picsum.photos/seed/mh/32/32' },
    imageUrl: 'https://i.imgur.com/7wM6JtA.png',
    category: 'Social Engineering',
    tagColor: 'pink',
    rating: 4,
  },
  {
    id: 'payload-virus',
    name: 'Payload Virus',
    description: 'Generates binary, web, scripting payloads and shellcode for security testing.',
    link: '#',
    author: { name: 'Marcos Henrique', avatarUrl: 'https://picsum.photos/seed/mh/32/32' },
    imageUrl: 'https://i.imgur.com/5lD3A0I.png',
    category: 'Exploitation Frameworks',
    tagColor: 'red',
    rating: 4,
  },
  {
    id: 'credmap',
    name: 'credmap',
    description: 'Tests leaked credentials across known sites to check for reused passwords automatically.',
    link: '#',
    author: { name: 'Bruce Campos', avatarUrl: 'https://picsum.photos/seed/bc/32/32' },
    imageUrl: 'https://i.imgur.com/3z1g4uF.png',
    category: 'Password Attacks',
    tagColor: 'red',
    rating: 4,
  },
  {
    id: 'http-observatory',
    name: 'HTTP Observatory',
    description: 'Scanner that checks websites for compliance with recommended security best practices.',
    link: '#',
    author: { name: 'Marcos Henrique', avatarUrl: 'https://picsum.photos/seed/mh/32/32' },
    imageUrl: 'https://i.imgur.com/9v8H1iX.png',
    category: 'Web Application Security',
    tagColor: 'blue',
    rating: 5,
  },
  {
    id: 'bearer',
    name: 'bearer',
    description: 'SAST scanner analyzing source code and data flows to find security risks.',
    link: '#',
    author: { name: 'Marcos Henrique', avatarUrl: 'https://picsum.photos/seed/mh/32/32' },
    imageUrl: 'https://i.imgur.com/fA7n6O8.png',
    category: 'DevSecOps Tools',
    tagColor: 'yellow',
    rating: 4,
  },
];
